export const User = [
  {
    first_name: "Mikayla Bailey",
    last_name: "Candace Terry",
    email: "bibendum@google.org",
    question1Assigned: true,
    question2Assigned: true,
    uniqueId: "testlinkl8vwntkf",
  },
  {
    first_name: "Neve Nelson",
    last_name: "Quentin Duffy",
    email: "primis@google.ca",
    question1Assigned: true,
    question2Assigned: true,
    uniqueId: "testlinkl8vsxrerntkf",
  },
  {
    first_name: "Tate Crosby",
    last_name: "Zelenia Hogan",
    email: "augue.malesuada.malesuada@aol.org",
    question1Assigned: true,
    question2Assigned: false,
    uniqueId: "testlinkl8vwntbmnbnmkf",
  },
  {
    first_name: "Griffin Mejia",
    last_name: "Lysandra Mcgowan",
    email: "integer@protonmail.couk",
    question1Assigned: true,
    question2Assigned: true,
    uniqueId: "testlinkl8vwnt334kf",
  },
];

export const Results = [
  {
    uniqueId: "testlinkl8vwnt334kf",
    social: {
      question: [
        "Please tell me what you see on the picture.",
        "Why do they react the way they do?",
        "Have you ever found yourself or experienced a similar situation? Please tell me about it.",
        "Describe the image below",
        "Please tell me what you see on the picture.",
      ],
      imageUrl: [
        "https://res.cloudinary.com/dmzkkz5jf/image/upload/v1665015500/a9qsgcw4gvhkusg4epfy.jpg",
        "https://res.cloudinary.com/dmzkkz5jf/image/upload/v1665015500/xfeqwygwh5nl9naifaky.jpg",
        "https://res.cloudinary.com/dmzkkz5jf/image/upload/v1665015500/a9qsgcw4gvhkusg4epfy.jpg",
        "https://res.cloudinary.com/dmzkkz5jf/image/upload/v1665009601/cfj8mmdfs9uctcdyeje1.jpg",
        "https://res.cloudinary.com/dmzkkz5jf/image/upload/v1665009601/eiibebmrdbimiq2hbseo.jpg",
      ],
      answer: [
        "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. ",
        "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. ",
        "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. ",
        "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. ",
        "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. ",
      ],
    },
    motivation: [
      "Szellemi ösztönzés",
      "Altruizmus",
      "Anyagiak",
      "Változatosság",
      "Függetlenség",
      "Presztízs",
      "Esztétikum",
      "Társas kapcsolatok",
      "Játékosság",
      "Önérvényesítés",
      "Hierarchia",
      "Humán értékek",
      "Munkateljesítmény",
      "Kreativitás",
      "Irányítás",
    ],
    answer: [3, 12, 6, 8, 9, 6, 13, 3, 8, 9, 10, 12, 3, 13, 7],
  },
];
